### PR TITLE
Fix licensing

### LINKED ISSUE #44: Fix licensing error by actually looking for LGPL

### PR DESCRIPTION
**Pull request by GraysonNocera**
I fixed the licensing, such that it actually looks for the licensing information in the README.

### CODE REVIEW

File: src/clone_repo.ts [hunk 1]
```diff
@@ -1,243 +1,355 @@
...
+): Promise<boolean> {
+  // Search through README for correct license in README
+
+  let searches: Array<RegExp> = [
+    /[Ll]+(esser\s)*[Gg]+(eneral\s)*[Pp]+(ublic\s)*[Ll]+(icense\s|icence\s)*\s*[Vv]+(ersion)*(\s)*(2\.[1-9]|3(\.[1-9])*)+/,
+    /\s*[Mm]+[Ii]+[Tt]+(\s|\.|!|\n)+/,
+    /\s*[Bb]+[Ss]+[Dd]+(\s|\.|!|\n)+/,
+    /[Aa](pache|PACHE)+/,
+    /\s*[Mm]+[Pp]+[Ll]+(\s|\.|!|\n)+/,
+  ];
```
Comment (khauersp) [inline src/clone_repo.ts:275]: The RegEx looks amazing

**Review by khauersp — APPROVED** [review]
Okay so do we need the log.txt file and the API json file in main? Not sure what they add.

**Review by 5han7anu-S — APPROVED** [review]
